plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.0'
}

group = 'net.cirsius'
version = '1'

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'org.yaml:snakeyaml:2.2'

    compileOnly 'net.md-5:bungeecord-api:1.21-R0.3'
    compileOnly 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'

    compileOnly 'com.github.nuvotifier.NuVotifier:nuvotifier-api:2.7.3'
    compileOnly 'com.github.nuvotifier.NuVotifier:nuvotifier-bungeecord:2.7.3'
    compileOnly 'com.github.nuvotifier.NuVotifier:nuvotifier-velocity:2.7.3'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

processResources {
    filesMatching(['bungee.yml', 'velocity-plugin.json']) {
        expand version: version
    }
}

shadowJar {
    archiveBaseName.set('TuffVote')
    archiveClassifier.set('')
    relocate 'org.yaml.snakeyaml', 'net.cirsius.tuffvote.libs.snakeyaml'
}

build {
    dependsOn shadowJar
}
