# use /commands.
# %username% is the placeholder for, usernames.

# services to accept votes from (leave empty to allow all)
services: []

commands:
  - "say %username% voted"

# sends a message to all players on the network when someone votes
broadcast_message: "%username% voted on %service%"